version: "3.9"

services:
  app:
    container_name: app_prod
    image: app-prod:1.0.0
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    entrypoint: ["npm", "start"]
    env_file: .env
    volumes:
      - .:/app
    networks:
      - wms-network

  web:
    container_name: web_server
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    entrypoint: ["nginx", "-g", "daemon off;"]
    depends_on:
      - app
    restart: always
    ports:
      - 9090:80
      - 443:443
    networks:
      - wms-network

networks:
  wms-network:
