version: "3.9"

services:
  app:
    container_name: app_dev
    image: app-dev:1.0.0
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    env_file: .env
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
